name: Atletas

on:
  push:
    branches:
      - main
  schedule:
    - cron: 15,45 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  atletas:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: football/predictions/probabilities
      filter: .data
      table: probabilities