name: Probabilities

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  etl:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: football/predictions/probabilities
      table: probabilities
      schema: probabilities.json
    secrets: inherit

  snapshot:
    uses: ./.github/workflows/snapshot.yml
    needs: etl
    with:
      table: probabilities
