name: Probabilities

on:
  push:
    branches:
      - main
  # schedule:
  #   - cron: 0 * * * *

permissions:
  contents: read
  id-token: write

jobs:
  atletas:
    uses: ./.github/workflows/etl.yml
    with:
      endpoint: football/predictions/probabilities
      table: probabilities
    secrets: inherit